stages:
  # - test
  - build
  - deploy

# test project:
#   stage: test
#   image: node:18
#   script:
#     - yarn install
#     - yarn test

build project: 
  stage: build
  image: node:18
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
      - build/  

netlify: 
  stage: deploy
  image: node:18
  script:
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod